### ISSUE TITLE
Typo in the blog post

### ISSUE THREAD

**Issue by minfawang** [ohanhi/elm-game-base#2]
First, thank you for the excellent write up. Very helpful to get me on board.

There is a typo in your [blog post](http://ohanhi.github.io/base-for-game-elm-017.html) under the section **Putting it all together: the update**.
This is the code you have in the post:
```elm
update : Msg -> Model -> ( Model, Cmd Msg )
update msg model =
    case msg of =   -- SHOULD NOT HAVE "=" HERE
        TimeUpdate dt ->
            ( applyPhysics dt model, Cmd.none )

        KeyDown keyCode ->
            ( keyDown keyCode model, Cmd.none )

        KeyUp keyCode ->
            ( keyUp keyCode model, Cmd.none )
```
The second "=" char should be removed.

**Comment by ohanhi** [comment]
Thanks, this is now fixed :)
